name: "Command /analyze"
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
  issues: write
jobs:
  run:
    if: ${{ github.event_name == 'workflow_dispatch' || startsWith(github.event.comment.body, '/analyze') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Debug event
        run: |
          echo "event=${{ github.event_name }}"
          echo "body='${{ github.event.comment.body || '' }}'"
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps (non-fatal first run)
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || true
      - name: Run analysis (adapt path if needed)
        run: |
          test -f scripts/analyze.py && python scripts/analyze.py || echo "no scripts/analyze.py"
