name: Build and Deploy Reports to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install quarkdown jupyter nbconvert pandas matplotlib

      - name: Generate Quarkdown HTML (if .qd file exists)
        run: |
          if [ -f reports/noema-report.qd ]; then
            echo "Generating HTML from noema-report.qd..."
            quarkdown build reports/noema-report.qd -o reports/noema-report.html
          else
            echo "⚠️ No .qd file found. Skipping build."
          fi

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
