name: Analyze on data push
on:
  push:
    paths:
      - "data/**"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Run analysis
        run: python scripts/analyze.py

      - name: Commit reports back
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add reports/
          git commit -m "chore: auto analysis reports [skip ci]" || echo "no changes"
          git push
