name: Analyze on data push
on:
  push
  workflow_dispatch

permissions:
  contents: write

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt
      - run: python scripts/analyze.py   # 或 scri/analyze.py，和你仓库一致
