name: Build & Publish Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install quarkdown openpyxl

      - name: Run analysis (generate REPORT.md, PNG, .qd)
        env:
          CLEAN: "1"     # clean up before starting (please change "retain history" to 0)
        run: |
          python scripts/analyze.py --n 0

      - name: Render Quarkdown -> HTML (reports/index.html)
        run: |
          quarkdown render noema-report.qd -o reports/index.html
          # Disable Pages from using Jekyll 
          touch reports/.nojekyll

      - name: Upload artifact (reports/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: reports

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
